### ISSUE TITLE
Missing webfiles or html files 

### ISSUE THREAD

**Issue by alonewolfx2** [ly0/esp8266-httpd#1]
Where is html files can you upload sample fs

**Comment by ly0** [comment]
Sorry, I removed FS from original _httpd_ currently. It only supports CGI now, temporarily at least.
First, I do not think demonstrating HTML is a good idea, since esp8266 seems very slow in transmitting data.
But now, I realize a FS is not a bad idea, I will integrate in few days.(it in todolist :) )
